### ISSUE TITLE
Issue with H2 database: Chunk xx not found

### ISSUE THREAD

**Issue by mauriciojost** [mauriciojost/main4ino-server#89]
```
+ cat /tmp/tmp.9qAjUeTnTO
org.flywaydb.core.internal.exception.FlywaySqlException: 
Unable to obtain connection from database: General error: "java.lang.IllegalStateException: Chunk 244288 not found [1.4.200/9]" [50000-200]
-------------------------------------------------------------------------------------------------------------------------------------------
SQL State  : HY000
Error Code : 50000
Message    : General error: "java.lang.IllegalStateException: Chunk 244288 not found [1.4.200/9]" [50000-200]

	at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:65)
	at org.flywaydb.core.internal.jdbc.JdbcConnectionFactory.<init>(JdbcConnectionFactory.java:80)
	at org.flywaydb.core.Flyway.execute(Flyway.java:456)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:159)
	at org.mauritania.main4ino.db.Database$.$anonfun$initialize$2(Database.scala:31)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:87)
	at cats.effect.internals.IORunLoop$.startCancelable(IORunLoop.scala:41)
	at cats.effect.internals.IOBracket$BracketStart.run(IOBracket.scala:90)
	at cats.effect.internals.Trampoline.cats$effect$internals$Trampoline$$immediateLoop(Trampoline.scala:67)
	at cats.effect.internals.Trampoline.startLoop(Trampoline.scala:35)
	at cats.effect.internals.TrampolineEC$JVMTrampoline.super$startLoop(TrampolineEC.scala:90)
	at cats.effect.internals.TrampolineEC$JVMTrampoline.$anonfun$startLoop$1(TrampolineEC.scala:90)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at cats.effect.internals.TrampolineEC$JVMTrampoline.startLoop(TrampolineEC.scala:90)
	at cats.effect.internals.Trampoline.execute(Trampoline.scala:43)
	at cats.effect.internals.TrampolineEC.execute(TrampolineEC.scala:42)
	at cats.effect.internals.IOBracket$BracketStart.apply(IOBracket.scala:70)
	at cats.effect.internals.IOBracket$BracketStart.apply(IOBracket.scala:50)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:141)
	at cats.effect.internals.IORunLoop$.start(IORunLoop.scala:34)
	at cats.effect.internals.IOBracket$.$anonfun$apply$1(IOBracket.scala:43)
	at cats.effect.internals.IOBracket$.$anonfun$apply$1$adapted(IOBracket.scala:33)
	at cats.effect.internals.IORunLoop$RestartCallback.start(IORunLoop.scala:352)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:124)
	at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:366)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:387)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:330)
	at cats.effect.internals.IOShift$Tick.run(IOShift.scala:36)
	at cats.effect.internals.PoolUtils$$anon$2$$anon$3.run(PoolUtils.scala:52)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: General error: "java.lang.IllegalStateException: Chunk 244288 not found [1.4.200/9]" [50000-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.message.DbException.convert(DbException.java:347)
	at org.h2.engine.Database.openDatabase(Database.java:333)
	at org.h2.engine.Database.<init>(Database.java:301)
	at org.h2.engine.Engine.openSession(Engine.java:74)
	at org.h2.engine.Engine.openSession(Engine.java:192)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at org.h2.engine.Engine.createSession(Engine.java:166)
	at org.h2.engine.Engine.createSession(Engine.java:29)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:354)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:473)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:554)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
	at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:56)
	... 33 more
Caused by: java.lang.IllegalStateException: Chunk 244288 not found [1.4.200/9]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at org.h2.mvstore.MVStore.getChunk(MVStore.java:1230)
	at org.h2.mvstore.MVStore.readBufferForPage(MVStore.java:1214)
	at org.h2.mvstore.MVStore.readPage(MVStore.java:2209)
	at org.h2.mvstore.MVMap.readPage(MVMap.java:672)
	at org.h2.mvstore.Page$NonLeaf.getChildPage(Page.java:1043)
	at org.h2.mvstore.Cursor.hasNext(Cursor.java:53)
	at org.h2.mvstore.MVMap$2$1.hasNext(MVMap.java:802)
	at org.h2.mvstore.db.LobStorageMap.init(LobStorageMap.java:109)
	at org.h2.engine.Database.open(Database.java:791)
	at org.h2.engine.Database.openDatabase(Database.java:307)
	... 51 more
++ is_port_free 8090
```

**Comment by mauriciojost** [comment]
Database with problem in: 
```
/home/mjost/opt/main4ino-server-wrapper-prd/db/investigation-issue-main4ino-server-89
```

**Comment by mauriciojost** [comment]
Could be related to a recent bump of version of flyway dependencies? Seems not.
